### ISSUE TITLE
QuickCheck-safe-0.1 does *not* build with QuickCheck-2.7

### ISSUE THREAD

**Issue by peti** [int-e/QuickCheck-safe#1]
Citing from http://hydra.cryp.to/build/793293/nixlog/1/raw:

```
src/Test/QuickCheck/Safe.hs:157:27: Not in scope: ‘scale’
```

**Comment by int-e** [comment]
Well, you modified the .cabal file.As is, the package really needs QuickCheck-2.8.

```
Dependency QuickCheck -any: using QuickCheck-2.7.6
```

**Comment by int-e** [comment]
Btw, I am in principle sympathetic to such compatibility problems, but for motivation I'd like some background on why QuickCheck-2.8 is problematic.

**Comment by int-e** [comment]
It turns out that `scale` was the only QuickCheck-2.8-specific function in all the code, which is simple enough to build from the existing `sized` and `resize` functions.

**Comment by peti** [comment]
Very cool. Thank you for the quick fix!
